name: Build 1.9.9

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    defaults:
      run:
        working-directory: v1.9.9   # your project is in this subfolder

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          brew update
          brew install ldid dpkg fakeroot gnu-tar md5sha1sum

      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos $HOME/theos
          git clone https://github.com/theos/sdks $HOME/theos/sdks

      - name: Fetch Orion (Swift hooking)
        run: |
          mkdir -p vendor
          [ -d vendor/Orion ] || git clone https://github.com/theos/orion vendor/Orion

      - name: Build package
        env:
          THEOS: ${{ runner.home }}/theos
        run: |
          make clean
          make package FINALPACKAGE=1 V=1

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBar15-rootless-debs
          path: v1.9.9/packages/*.deb
