name: Build AndroidBar15 (subdir)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix maintainer script perms
        run: |
          chmod 0755 with-working-buttons/layout/DEBIAN/postinst || true

      - name: Set up Theos
        uses: Randomblock1/theos-action@v1

      - name: Build package
        run: |
          make -C with-working-buttons package

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: debs
          path: with-working-buttons/packages/*.deb
