name: Build AndroidBar15
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - name: Fix maintainer script perms
        run: chmod 0755 layout/DEBIAN/postinst
      - name: Set up Theos
        uses: Randomblock1/theos-action@v1
      - name: Build package
        run: make package
      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: debs
          path: packages/*.deb
